/*
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFzoMa0Qn3hH_WFT2qhcmnJ_cWN5GmjVM',
    appId: '1:496441455277:android:23d1d1089abd3bbc774c24',
    messagingSenderId: '496441455277',
    projectId: 'c2cpatient-d4526',
    storageBucket: 'c2cpatient-d4526.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARzj9bC7XvdxuxKDW2-mdnhpRpzoXwxnQ',
    appId: '1:496441455277:ios:7534e179dd8d22ca774c24',
    messagingSenderId: '496441455277',
    projectId: 'c2cpatient-d4526',
    storageBucket: 'c2cpatient-d4526.appspot.com',
    iosBundleId: 'com.example.care2care',
  );

}*/
// import 'package:firebase_core/firebase_core.dart';
//
// class DefaultFirebaseOptions {
//   static FirebaseOptions get care2care {
//     return const FirebaseOptions(
//       apiKey: 'AIzaSyBFzoMa0Qn3hH_WFT2qhcmnJ_cWN5GmjVM',
//       appId: '1:496441455277:android:23d1d1089abd3bbc774c24',
//       messagingSenderId: '496441455277',
//       projectId: 'c2cpatient-d4526',
//       storageBucket: 'c2cpatient-d4526.appspot.com',
//     );
//   }
//
//   static FirebaseOptions get care2caretaker {
//     return const FirebaseOptions(
//       apiKey: 'AIzaSyBFzoMa0Qn3hH_WFT2qhcmnJ_cWN5GmjVM',
//       appId: '1:496441455277:android:662af5d3bc954389774c24',
//       messagingSenderId: '496441455277',
//       projectId: 'c2cpatient-d4526',
//       storageBucket: 'c2cpatient-d4526.appspot.com',
//     );
//   }
//
//   static FirebaseOptions get currentPlatform {
//     // Modify this logic based on the package name or other criteria to select the correct options
//     const String packageName = "com.example.care2caretaker"; // Change based on the running app
//     if (packageName == "com.example.care2care") {
//       return care2care;
//     } else {
//       return care2caretaker;
//     }
//   }
// }
import 'package:firebase_core/firebase_core.dart';
import 'dart:io';

class DefaultFirebaseOptions {

  static FirebaseOptions get care2care {

    bool android = Platform.isAndroid;

    if(android){
      return const FirebaseOptions(
        apiKey: 'AIzaSyBFzoMa0Qn3hH_WFT2qhcmnJ_cWN5GmjVM',
        appId: '1:496441455277:android:23d1d1089abd3bbc774c24',
        messagingSenderId: '496441455277',
        projectId: 'c2cpatient-d4526',
        storageBucket: 'c2cpatient-d4526.appspot.com',
      );
    }
    return const FirebaseOptions(
      apiKey: 'AIzaSyARzj9bC7XvdxuxKDW2-mdnhpRpzoXwxnQ',
      appId: '1:496441455277:ios:1a44c410aa9835ea774c24',
      messagingSenderId: '496441455277',
      projectId: 'c2cpatient-d4526',
      storageBucket: 'c2cpatient-d4526.appspot.com',
    );
  }

  static FirebaseOptions get currentPlatform {

    return care2care;
  }
}